language: csharp

mono:
  - latest

solution: CodeTools.sln

env:
 global:
  - EnableNuGetPackageRestore=true

install:
  - nuget restore CodeTools.sln

script:
 - xbuild /property:Configuration=Debug CodeTools.sln
 - xbuild /property:Configuration=Release CodeTools.sln
