language: csharp

mono:
  - latest

solution: CSharpTools.sln

env:
 global:
  - EnableNuGetPackageRestore=true 

install:
  - nuget restore ToolBelt.sln

script:
 - xbuild /property:Configuration=Debug CSharpTools.sln
 - xbuild /property:Configuration=Release CSharpTools.sln
