#!/bin/bash
# Output a list of all the CodeTools
echo "cleaner   - Cleans C# project directories"
echo "doozer    - Displays all TODO's in all C# files"
echo "ender     - Changes line endings of text files"
echo "lindex    - Creates a binary line index file"
echo "projector - Copies and renames a C# solution tree"
echo "spacer    - Fixes spaces and tabs in text files"
echo "strapper  - Creates strongly typed resource wrappers"
echo "vamper    - Updates version information"
echo "popper    - Swaps out NuGet projects for local builds"
