#!/bin/bash
# Output a list of all the CSharpTools
echo "cleaner   - Cleans C# project directories"
echo "doozer    - Displays all TODO's in all C# files"
echo "lindex    - Creates a binary line index file"
echo "projector - Copies and renames a C# solution tree"
echo "strapper  - Creates strongly typed resource wrappers"
echo "popper    - Swaps out NuGet projects for local builds"
